[package]
name = "protos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic-build = "0.7"
tonic = "0.7"
prost-types = "0.10"
prost = "0.10"
dotenv = "0.15"
